//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public string MaKhachHang { get; set; }
        public System.DateTime NgayLap { get; set; }
        public decimal TongTien { get; set; }
        public bool DaThanhToan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
