//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDon = new HashSet<ChiTietHoaDon>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public decimal GiaSP { get; set; }
        public string HinhSP { get; set; }
        public int LuotXem { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<System.DateTime> NgayNhapKho { get; set; }
        public string MoTaNgan { get; set; }
        public string CauHinh { get; set; }
        public string MoTa { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<int> MaHangSX { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<bool> ConKinhDoanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDon { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
